### ISSUE TITLE
Error exporting Javadoc

### ISSUE THREAD

**Issue by Kekko01** [madhavd1/vscode-javadoc-tools#13]
Hi, I have an error when I try to export the Javadoc of the project, here is the code with the error:

```
In riga:1 car:94
+ ... Eclipse Foundation\jdk-11.0.12.7-hotspot\bin\javadoc" -public -d "c:\ ...
+                                                           ~~~~~~~
Token '-public' imprevisto nell'espressione o nell'istruzione.
In riga:1 car:102
+ ... ipse Foundation\jdk-11.0.12.7-hotspot\bin\javadoc" -public -d "c:\Use ...
+                                                                ~~
Token '-d' imprevisto nell'espressione o nell'istruzione.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```
What can I do?

**Comment by madhavd1** [comment]
Hi @Kekko01 ,
Are you using pwsh?

I've just pushed v1.5.0 which should has a new property to fix this issue.
- Added a new Property `javadoc-tools.generateJavadoc.isUsingPwsh` which can be set to true to support Powershell javadoc export.

Can you please try and let me know?

Madhva
