### ISSUE TITLE
Can't export: path separator issues on mac (probably also linux)

### ISSUE THREAD

**Issue by asmfstatoil** [madhavd1/vscode-javadoc-tools#15]
The paths in the application command strings for generating javadocs are hardcoding windows-style path separators like:

`srcFolder = vscode.workspace.rootPath + '\\src';` from https://github.com/madhavd1/vscode-javadoc-tools/blob/master/src/extension.ts

Please consider replacing the `\\` with the correct os path separator, possibly as as suggested in the link below 
https://stackoverflow.com/questions/125813/how-to-determine-the-os-path-separator-in-javascript

**Comment by ProfPaulB** [comment]
When will this be fixed in the marketplace? Seems like the fix is quite trivial. I'd love to be able to use this with my students, but there are many using Mac (including me).

**Comment by madhavd1** [comment]
Hi, I will try to test the fix provided by @eecarrier merged and deployed within the next 1-2 weeks.

**Comment by lusacramento** [comment]
problem linux too.

**Comment by leranjun** [comment]
> Hi, I will try to test the fix provided by @eecarrier merged and deployed within the next 1-2 weeks.

Any updates on this?

**Comment by madhavd1** [comment]
This has been fixed with v1.6.0. It is available on the Marketplace now.
